## <font color="maroon"><h4 align="center">Handling Missing Data - fillna, interpolate, dropna: Exercise</font>

## <font color="blue">About the data</font>
- The file **fruits_data.csv** lists the monthly prices of Apple, Banana, Grapes, Mango, and Water Melons from January to October 2022.
- Your task is to fill in the missing values according to the given instructions.

In [2]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the csv file 'fruits_data.csv' into the dataframe 'df'.
- show the number of rows and columns in it.
- list all the columns present in the dataframe.
- show the dataframe

In [10]:
#read the csv file

df = pd.read_csv('fruits_data.csv')

#show the number of rows and columns

print(df.shape)

#list all the columns

print(len(df.columns))


#show the dataframe
print(df)

(10, 6)
6
         date  apple(1kg)  banana(1 dozen)  grapes(1kg)  mango(1kg)  \
0  01-01-2022       230.0             46.0         65.0       184.0
1  01-02-2022       237.0             50.0         72.0       173.0
2  01-03-2022       259.0              NaN          NaN         NaN
3  01-04-2022         NaN             41.0         75.0       175.0
4  01-05-2022       240.0             48.0          NaN       185.0
5  01-06-2022       234.0             45.0         66.0       194.0
6  01-07-2022         NaN              NaN         70.0       174.0
7  01-08-2022       236.0             46.0         66.0       187.0
8  01-09-2022       232.0             41.0         71.0         NaN
9  01-10-2022       240.0             48.0          NaN       198.0

   Water Melons(1)
0              NaN
1             72.0
2             93.0
3             74.0
4             84.0
5             93.0
6              NaN
7             86.0
8             93.0
9             97.0

### <font color="purple">**Question2**</font>
- Fill all the null values in the dataframe with '-1' and store the result to variable 'new_df'.

In [11]:
#fill null values with -1 and store it to 'new_df'
 
new_df = df.fillna(-1)

#show the dataframe 'new_df'
 
print(new_df)

         date  apple(1kg)  banana(1 dozen)  grapes(1kg)  mango(1kg)  \
0  01-01-2022       230.0             46.0         65.0       184.0
1  01-02-2022       237.0             50.0         72.0       173.0
2  01-03-2022       259.0             -1.0         -1.0        -1.0
3  01-04-2022        -1.0             41.0         75.0       175.0
4  01-05-2022       240.0             48.0         -1.0       185.0
5  01-06-2022       234.0             45.0         66.0       194.0
6  01-07-2022        -1.0             -1.0         70.0       174.0
7  01-08-2022       236.0             46.0         66.0       187.0
8  01-09-2022       232.0             41.0         71.0        -1.0
9  01-10-2022       240.0             48.0         -1.0       198.0

   Water Melons(1)
0             -1.0
1             72.0
2             93.0
3             74.0
4             84.0
5             93.0
6             -1.0
7             86.0
8             93.0
9             97.0

### <font color="purple">**Question3**</font>
Fill the null values in respective columns like below:

    - apple(1kg): Mean value of that column
    - banana(1 dozen): Mean value of that column
    - grapes(1kg): Median value of that column
    - mango(1kg): Median value of that column
    - Water Melons(1): Fill null values with "Not Available".
    
Finally store the output to 'new_df' variable

In [14]:
#write the code to find mean

mean = df['apple(1kg)'].mean()

print(mean)

#store the result to 'new_df' variable 

new_df = df['apple(1kg)'].fillna(mean)

#show the dataframe 'new_df'
new_df

238.5

0    230.0
1    237.0
2    259.0
3    238.5
4    240.0
5    234.0
6    238.5
7    236.0
8    232.0
9    240.0
Name: apple(1kg), dtype: float64

### <font color="purple">**Question4**</font>

- Fill the null values with the non-null value before it (Forward fill method)
- Store the result in 'new_df'.

In [24]:
#fill null values using 'ffill'

new_df = df.ffill()

#show the dataframe 'new_df'
print(new_df)

         date  apple(1kg)  banana(1 dozen)  grapes(1kg)  mango(1kg)  \
0  01-01-2022       230.0             46.0         65.0       184.0
1  01-02-2022       237.0             50.0         72.0       173.0
2  01-03-2022       259.0             50.0         72.0       173.0
3  01-04-2022       259.0             41.0         75.0       175.0
4  01-05-2022       240.0             48.0         75.0       185.0
5  01-06-2022       234.0             45.0         66.0       194.0
6  01-07-2022       234.0             45.0         70.0       174.0
7  01-08-2022       236.0             46.0         66.0       187.0
8  01-09-2022       232.0             41.0         71.0       187.0
9  01-10-2022       240.0             48.0         71.0       198.0

   Water Melons(1)
0              NaN
1             72.0
2             93.0
3             74.0
4             84.0
5             93.0
6             93.0
7             86.0
8             93.0
9             97.0

### <font color="purple">**Question5**</font>
- Drop the rows if it does not contain atleast 4 non-null values (use the concept of thresholding).
- store the result in 'new_df'

In [26]:
#write the code here
new_df = df.dropna(thresh=4)


#show the dataframe 'new_df'

new_df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.0,65.0,184.0,NaN
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
3,01-04-2022,NaN,41.0,75.0,175.0,74.0
4,01-05-2022,240.0,48.0,NaN,185.0,84.0
5,01-06-2022,234.0,45.0,66.0,194.0,93.0
7,01-08-2022,236.0,46.0,66.0,187.0,86.0
8,01-09-2022,232.0,41.0,71.0,NaN,93.0
9,01-10-2022,240.0,48.0,NaN,198.0,97.0

### <font color="purple">**Question6**</font>


- Finally, remove the row if it contain null value and store the result in 'new_df'
- save that dataframe to csv:'final_data.csv' and make sure to set index to False

In [29]:
#write the code here

new_df = df.dropna()


#show the dataframe 'new_df'

new_df

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
5,01-06-2022,234.0,45.0,66.0,194.0,93.0
7,01-08-2022,236.0,46.0,66.0,187.0,86.0

In [30]:
#save the dataframe to 'final_data.csv'
new_df.to_csv('final_data.csv')