In [4]:
import pandas as pd 
import numpy as np

## Creating Data Frame


A DataFrame is a two-dimensional data structure with rows and columns used to store and analyze tabular data in pandas. It is similar to a spreadsheet or database table.

Benefits of DataFrame

Organized Data Storage
Stores data in a structured table format (rows and columns).

Easy Data Manipulation
Allows filtering, sorting, and modifying data easily.

Handles Large Datasets
Can process large amounts of data efficiently.

Powerful Data Analysis
Supports operations like grouping, aggregation, and statistics.

Integration with Python Tools
Works well with libraries for visualization and machine learning.












## Benefits of pandas 

Easy to read data
You can quickly load files like Excel or CSV.
Example:

df = pd.read_csv("data.csv")

Easy to filter data
You can find specific rows easily.
Example: show people with age > 20

df[df["Age"] > 20]

Easy calculations
You can calculate totals, averages, etc.
Example:

df["Age"].mean()

Easy data cleaning
Helps remove or fill missing values.
Example:

df.dropna()

Handles large data
Works well with large datasets that are hard to manage in Excel.

In [5]:
sheet = pd.DataFrame(data= np.arange(1,21).reshape(4,5),index = ["Row 1","Row 2","Row 3","Row 4"],columns= ["Column 1","Column 2","Column 3","Column 4","Column 5"])

In [ ]:
sheet.head() 

# shows top 5 records

       Column 1  Column 2  Column 3  Column 4  Column 5
Row 1         1         2         3         4         5
Row 2         6         7         8         9        10
Row 3        11        12        13        14        15
Row 4        16        17        18        19        20

In [21]:
sheet.tail()

# shows last 5 records

       Column 1  Column 2  Column 3  Column 4  Column 5
Row 1         1         2         3         4         5
Row 2         6         7         8         9        10
Row 3        11        12        13        14        15
Row 4        16        17        18        19        20

In [22]:
sheet.head(3)

# want to see top 3 records

       Column 1  Column 2  Column 3  Column 4  Column 5
Row 1         1         2         3         4         5
Row 2         6         7         8         9        10
Row 3        11        12        13        14        15

In [23]:
type(sheet)

pandas.DataFrame

In [24]:
sheet.info()

<class 'pandas.DataFrame'>
Index: 4 entries, Row 1 to Row 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column 1  4 non-null      int64
 1   Column 2  4 non-null      int64
 2   Column 3  4 non-null      int64
 3   Column 4  4 non-null      int64
 4   Column 5  4 non-null      int64
dtypes: int64(5)
memory usage: 192.0+ bytes

In [25]:
sheet.describe()

        Column 1   Column 2   Column 3   Column 4   Column 5
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    8.500000   9.500000  10.500000  11.500000  12.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     1.000000   2.000000   3.000000   4.000000   5.000000
25%     4.750000   5.750000   6.750000   7.750000   8.750000
50%     8.500000   9.500000  10.500000  11.500000  12.500000
75%    12.250000  13.250000  14.250000  15.250000  16.250000
max    16.000000  17.000000  18.000000  19.000000  20.000000

In [33]:
sheet[['Column 1','Column 2']]

       Column 1  Column 2
Row 1         1         2
Row 2         6         7
Row 3        11        12
Row 4        16        17

In [46]:
sheet.iloc[:,1]

# another type of getting element using iloc function with the use of index

Row 1     2
Row 2     7
Row 3    12
Row 4    17
Name: Column 2, dtype: int64

In [45]:
type(sheet[['Column 1','Column 2']])

pandas.DataFrame

In [36]:
type(sheet['Column 1'])

pandas.Series

## Panda vs Series 

A Panda is made of multiple rows and column whereas series is made up of either one row or one column

In [8]:
sheet.loc['Row 3']

# 2nd type of getting element using loc function

Column 1    11
Column 2    12
Column 3    13
Column 4    14
Column 5    15
Name: Row 3, dtype: int64

In [6]:
# to convert dataframe into arrays 
sheet.iloc[:,1:].values

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [7]:
sheet['Column 3'].value_counts()

Column 3
3     1
8     1
13    1
18    1
Name: count, dtype: int64