In [43]:
import pandas as pd 
import json

from io import StringIO

In [10]:
data = '{"country name":"India" , "population" :"150 crores"}'
json.loads(data)

{'country name': 'India', 'population': '150 crores'}

In [5]:
type(data)

str

In [ ]:
df = pd.read_json(StringIO(data), typ="series")

country name         India
population      150 crores
dtype: str

In [19]:
df = pd.read_json(StringIO(data),orient='index')
df

                       0
country name       India
population    150 crores

In [32]:
df = pd.DataFrame([[1,3],[3,4]],
                  index= ['row 1','row 2'],
                  columns=['column 1', 'column 2'])
df

       column 1  column 2
row 1         1         3
row 2         3         4

In [35]:
df.to_json()

'{"column 1":{"row 1":1,"row 2":3},"column 2":{"row 1":3,"row 2":4}}'

In [34]:
df.to_json(orient='index')

'{"row 1":{"column 1":1,"column 2":3},"row 2":{"column 1":3,"column 2":4}}'

In [36]:
df.to_json(orient='columns')

# priority on column

'{"column 1":{"row 1":1,"row 2":3},"column 2":{"row 1":3,"row 2":4}}'

In [37]:
df.to_json(orient='split')

'{"columns":["column 1","column 2"],"index":["row 1","row 2"],"data":[[1,3],[3,4]]}'

In [39]:
df.to_json(orient='records')

'[{"column 1":1,"column 2":3},{"column 1":3,"column 2":4}]'