In [1]:
from io import StringIO

In [9]:
import pandas as pd 
df = pd.read_csv('example.csv')

In [ ]:
df.head()

   id   name  score
0   1  Sahil     95
1   2   Alex     88
2   3   Riya     92

In [11]:
df.tail()

   id   name  score
0   1  Sahil     95
1   2   Alex     88
2   3   Riya     92

In [12]:
df.tail(2)

   id  name  score
1   2  Alex     88
2   3  Riya     92

In [ ]:
# if you need only few column which you need 


df = pd.read_csv('example.csv',usecols=['id','name'])
df.head()

   id   name
0   1  Sahil
1   2   Alex
2   3   Riya

In [ ]:
#  convert the file to csv

df.to_csv('test.csv')

In [20]:
# want to save file without index 

df.to_csv('withoutindex.csv', index=False)

In [25]:
# create a file 

data = ( 'a , b ,  c , d \n'
        '2,3,4,5 \n'
        '9,10,11')

pd.read_csv(StringIO(data))

   a    b     c    d
0   2    3     4  5.0
1   9   10    11  NaN

In [35]:
pd.read_csv(StringIO(data),dtype='float')

    a     b     c    d
0  2.0   3.0   4.0  5.0
1  9.0  10.0  11.0  NaN

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3 non-null      int64
 1   name    3 non-null      str
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [39]:
df.isnull().sum()

# to know which has null values , currently every element has some value

id      0
name    0
dtype: int64

In [42]:
pd.read_csv(StringIO(data),dtype={'a':int,'b':float})

# different data type for different values

   a    b     c    d
0   2    3     4  5.0
1   9   10    11  NaN

id      int64
name      str
dtype: object